[network.stream2.task0.subtask0.thread0]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	thread_dim = 1
    type = "AIC"
    block_dim = 1
    core_list = [0]
	start_cycle = 451
	end_cycle = 140699
	duration = 140248
	first_blk_start_cycle = 454
